### ISSUE TITLE
configure file for training fbwq_half

### ISSUE THREAD

**Issue by lihuiliullh** [malllabiisc/EmbedKGQA#108]
would you mind share the configure file for training fbwq_half and fbwq_full?
Also, why do you name it fbwq_half instead of WebQuestionsSP_half?

Another thing is 
May I know how you pre-train MetaQA data? Do you use the code in directory "train_embeddings" to learn the embedding? If so, can you share the command of running the main.py with me?

**Comment by lihuiliullh** [comment]
May I know why you don't kge to train MetaQA?

**Comment by apoorvumang** [comment]
Fbwq = freebasewebquestions. Other names might have been better

We used that code to train embeddings for MetaQA. Since that code isn't scalable, we used libkge for fbwq

In hindsight, it would have been better to use libkge for all datasets

If I remember correctly, in one of the closed issues a config file has been shared. If you can look for it there it would be great

**Comment by lihuiliullh** [comment]
Yes, I checked that issue. https://github.com/malllabiisc/EmbedKGQA/issues/97

But I don't know whether it could achieve the same performance as your model. Because there are many parameters in the file, e.g., learning_rate, max_epochs, batch_size, drop out rate. It would be great if you could share your original file.

**Comment by apoorvumang** [comment]
Let me look for it and I'll get back to you

**Comment by lihuiliullh** [comment]
Thanks. Also, can you share the command line you use to pre-train MetaQA?

**Comment by apoorvumang** [comment]
This should be the correct config

```
complex:
  entity_embedder:
    dropout: 0.44299429655075073
    regularize_weight: 7.830760727899156e-12
  relation_embedder:
    dropout: -0.4746062345802784
    regularize_weight: 1.182876478423781e-10
dataset:
  name: fbwq_half
eval:
  batch_size: 200
  chunk_size: 25000
  num_workers: 2
import:
- complex
lookup_embedder:
  dim: 400
  initialize_args:
    normal_:
      mean: 0.0
      std: 5.8970567449527816e-05
  regularize_args:
    p: 1
    weighted: true
  sparse: true
model: complex
negative_sampling:
  implementation: batch
  num_samples:
    o: 7851
    s: 2176
  shared: true
  with_replacement: false
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 1
    threshold: 0.0001
  max_epochs: 200
  num_workers: 8
  optimizer_args:
    lr: 0.6560544891789137
  type: negative_sampling
valid:
  early_stopping:
    min_threshold:
      epochs: 10
      metric_value: 0.1
    patience: 10

```
